name: Sync repo to Gitee

on:
  workflow_call:
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  sync-gitee:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          source-repo: 'git@github.com:zotero-chinese/zotero-plugins.git'
          destination-repo: 'git@gitee.com:northword/zotero-plugins.git'
